
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const ContactPage = () => {
    return (
        <div>
            <h1>This is my contact Page</h1>
        </div>
    );
};

export default ContactPage;