
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashboardPage = () => {
    return (
        <div>
            <h1>This is Dashboard</h1>
        </div>
    );
};

export default DashboardPage;